language: node_js
node_js:
  - 16

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build
  - docker tag udagram-api-feed 0987432592345457/udagram-api-feed:v5
  - docker tag udagram-api-user 0987432592345457/udagram-api-user:v5
  - docker tag udagram-frontend 0987432592345457/udagram-frontend:v5
  - docker tag udagram-reverseproxy 0987432592345457/udagram-reverseproxy:v5

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - docker image ls
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push 0987432592345457/udagram-api-feed:v5
  - docker push 0987432592345457/udagram-api-user:v5
  - docker push 0987432592345457/udagram-frontend:v5
  - docker push 0987432592345457/udagram-reverseproxy:v5