# .circleci/config.yml file
version: 2.1

jobs:
  mybuildjob:            # job name
    docker:         # executor type
      - image: cimg/base:current # Docker image that installs Docker and has Git,
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Install dependencies
          command: echo "No need to install anything. \n Just build and push the Docker image."
      - run:
          name: Build Docker images
          command: |
            echo "Inside the Build and push Docker image step"
            docker --version # print the version for logging
            docker-compose -f docker-compose-build.yaml build --parallel
      - run:
          name: Tag the docker images
          command: |
            echo "Inside the Tag the docker images step"
            docker tag udagram-api-feed 0987432592345457/udagram-api-feed
            docker tag udagram-api-user 0987432592345457/udagram-api-user
            docker tag udagram-frontend 0987432592345457/udagram-frontend
            docker tag reverseproxy 0987432592345457/udagram-reverseproxy
      - run:
          name: Push Docker images
          command: |
            echo "Inside the Push Docker images step"
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push 0987432592345457/udagram-api-feed
            docker push 0987432592345457/udagram-api-user
            docker push 0987432592345457/udagram-frontend
            docker push 0987432592345457/udagram-reverseproxy

# Orchestrate jobs using workflows.
workflows:
  version: 2
  build-and-push-docker-hub:
    jobs:
      - mybuildjob